global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spring-observability"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          env: "dev"
          instance: "server1"